apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-deployment
  labels:
    app: restapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: restapi
  template:
    metadata:
      labels:
        app: restapi 
    spec:
      containers:
      - name: restapi-todo
        image: sunnyboysb/rest-api
        ports:
        - containerPort: 5000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: restapi-service
spec:
  selector:
    app: restapi 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 31110
